#!/usr/bin/env bash
#
# rebuilds default flake in dotfiles and prints errors in a readable way.
# rebuild [commit msg]
#
# source: https://www.youtube.com/watch?v=CwfKlX3rA6E

set -e
pushd ~/dotfiles

alejandra . &>/dev/null

#git diff -U0 *.nix

echo "NixOS Rebuilding..."

sudo nixos-rebuild switch --flake .#default \
	&>nixos.switch.log || \
	(cat nixos-switch.log | grep --color error && false)

gen=$(nixos-rebuild list-generations | grep current)

popd
